"""Generate FastMCP server Python code from a list of tool definitions."""

from typing import Any


def _python_type(json_type: str) -> str:
    return {"string": "str", "number": "float", "integer": "int", "boolean": "bool", "array": "list", "object": "dict"}.get(json_type, "str")


def _default_return(json_type: str) -> str:
    return {"string": '""', "number": "0.0", "integer": "0", "boolean": "False", "array": "[]", "object": "{}"}.get(json_type, '""')


def generate(server_name: str, tools: list[dict[str, Any]]) -> str:
    """
    tools: list of {name, description, parameters: [{name, type, description, required}], return_type}
    """
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""',
        f'{server_name} MCP server - generated by MCP Explorer.',
        '"""',
        "",
        "from mcp.server.fastmcp import FastMCP",
        "",
        f'mcp = FastMCP("{server_name}")',
        "",
    ]

    for tool in tools:
        tool_name = tool["name"].replace(" ", "_").lower()
        description = tool.get("description", "")
        params = tool.get("parameters", [])
        return_type = tool.get("return_type", "string")

        # Build function signature
        args = []
        for p in params:
            py_type = _python_type(p.get("type", "string"))
            args.append(f'{p["name"]}: {py_type}')

        py_return = _python_type(return_type)
        sig = f'def {tool_name}({", ".join(args)}) -> {py_return}:'

        lines.append("@mcp.tool()")
        lines.append(sig)

        # Docstring
        if description:
            lines.append(f'    """{description}"""')

        # Stub: return a message showing the tool was called with its arguments
        if params:
            # Build f-string interpolations like: name={name}, age={age}
            fparts = ", ".join(p["name"] + "={" + p["name"] + "}" for p in params)
            lines.append(f'    return f"[stub] {tool_name} called with: {fparts}"')
        else:
            lines.append(f'    return "[stub] {tool_name} called (no arguments)"')
        lines.append("")
        lines.append("")

    lines += [
        'if __name__ == "__main__":',
        "    mcp.run()",
        "",
    ]

    return "\n".join(lines)
